language: erlang
notifications:
  recipients:
    - patrick.detlefsen@gmail.com
    - kurt.r.williams@gmail.com
otp_release:
  - 17.0
addons:
  postgresql: "9.3"
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - MIX_ENV=test mix do deps.get
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres travis_ci_test < schema/schema.sql
script:
  - MIX_ENV=all mix test
